openapi: 3.0.1
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  termsOfService: http://swagger.io/terms/
  version: 1.0.0
servers:
  - url: http://localhost:3001/api/v1
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      requestBody:
        description: Login Payload
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/Login"
        required: true
      responses:
        "200":
          description: Login Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "400":
          description: Invalid Fields
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      requestBody:
        description: Signup Payload
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/User"
        required: true
      responses:
        "200":
          description: Signup Successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Invalid Fields
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      x-codegen-request-body-name: body
  /user/profile:
    put:
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      requestBody:
        description: Update user profile attributes
        content:
          "*/*":
            schema:
              $ref: "#/components/schemas/UserProfile"
        required: true
      responses:
        "200":
          description: User profile retrieved successully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Invalid Fields
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      security:
        - Bearer: []
      x-codegen-request-body-name: body
    post:
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      responses:
        "200":
          description: User profile retrieved successully
          content:
            "*/*":
              schema:
                $ref: "#/components/schemas/ApiResponse"
        "400":
          description: Invalid Fields
          content: {}
        "500":
          description: Internal Server Error
          content: {}
      security:
        - Bearer: []
  /bank/accounts:
    get:
      tags:
        - Bank Module
      summary: User Bank Accounts API
      description: Returns all bank accounts
      responses:
        "200":
          description: Returned all bank accounts successully
          content:
            "application/json":
              schema:
                type: array
                items:
                  type: object
                  properties:
                    accountId:
                      type: string
                      example: "1"
                    accountName:
                      type: string
                      example: "Argent Bank Checking (x3448)"
                    accountBalance:
                      type: number
                      example: 48,098.43
        "500":
          description: Internal Server Error
          content: {}
      security:
        - Bearer: []
  /bank/transactions:
    get:
      tags:
        - Bank Module
      summary: User Bank Transactions API
      description: Returns all transactions
      parameters:
        - name: accountId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Returned all transactions successully
          content:
            "application/json":
              schema:
                type: array
                items:
                  type: object
                  properties:
                    transactionId:
                      type: string
                      example: "1"
                    date:
                      type: string
                      example: "27/02/20"
                    description:
                      type: string
                      example: "Golden Sun Bakery"
                    amount:
                      type: number
                      format: double
                      example: 8.00
                    type:
                      type: string
                      example: "Electronic"
                    category:
                      type: string
                      example: "Food"
                    note:
                      type: string
                      example: "Lorem ipsum"
        "500":
          description: Internal Server Error
          content: {}
      security:
        - Bearer: []
    put:
      tags:
        - Bank Module
      summary: User Bank Transactions API
      description: Modify transaction category and note
      parameters:
        - name: transactionId
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Transaction modified successully
          content:
            "application/json":
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      example: "1"
                    category:
                      type: string
                      example: "Food"
                    note:
                      type: string
                      example: "Lorem ipsum"
        "500":
          description: Internal Server Error
          content: {}
      security:
        - Bearer: []
components:
  schemas:
    User:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
        firstName:
          type: string
          description: user first name
        lastName:
          type: string
          description: user last name
        userName:
          type: string
          description: user public name
    Login:
      type: object
      properties:
        email:
          type: string
          description: user email
        password:
          type: string
          description: user password
    ApiResponse:
      type: object
      properties:
        status:
          type: integer
        message:
          type: string
        body:
          type: object
          properties:
            id:
              type: string
            email:
              type: string
    LoginResponse:
      type: object
      properties:
        token:
          type: string
    UserProfile:
      type: object
      properties:
        userName:
          type: string
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
x-original-swagger-version: "2.0"
